/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in camp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>camp.t_camp_pk_seq</code>
     */
    public static final Sequence<Long> T_CAMP_PK_SEQ = new SequenceImpl<Long>("t_camp_pk_seq", Camp.CAMP, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>camp.t_location_pk_seq</code>
     */
    public static final Sequence<Long> T_LOCATION_PK_SEQ = new SequenceImpl<Long>("t_location_pk_seq", Camp.CAMP, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>camp.t_profile_pk_seq</code>
     */
    public static final Sequence<Long> T_PROFILE_PK_SEQ = new SequenceImpl<Long>("t_profile_pk_seq", Camp.CAMP, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>camp.t_sales_pk_seq</code>
     */
    public static final Sequence<Long> T_SALES_PK_SEQ = new SequenceImpl<Long>("t_sales_pk_seq", Camp.CAMP, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
