/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq;


import de.jottyfan.camporganizer.db.jooq.tables.TCamp;
import de.jottyfan.camporganizer.db.jooq.tables.TLocation;
import de.jottyfan.camporganizer.db.jooq.tables.TProfile;
import de.jottyfan.camporganizer.db.jooq.tables.TProfilerole;
import de.jottyfan.camporganizer.db.jooq.tables.TSales;
import de.jottyfan.camporganizer.db.jooq.tables.TSalescontent;
import de.jottyfan.camporganizer.db.jooq.tables.TSalescontenttype;
import de.jottyfan.camporganizer.db.jooq.tables.VBudget;
import de.jottyfan.camporganizer.db.jooq.tables.VCamp;
import de.jottyfan.camporganizer.db.jooq.tables.VProfile;
import de.jottyfan.camporganizer.db.jooq.tables.VRole;
import de.jottyfan.camporganizer.db.jooq.tables.VSales;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in camp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>camp.t_camp</code>.
     */
    public static final TCamp T_CAMP = de.jottyfan.camporganizer.db.jooq.tables.TCamp.T_CAMP;

    /**
     * The table <code>camp.t_location</code>.
     */
    public static final TLocation T_LOCATION = de.jottyfan.camporganizer.db.jooq.tables.TLocation.T_LOCATION;

    /**
     * The table <code>camp.t_profile</code>.
     */
    public static final TProfile T_PROFILE = de.jottyfan.camporganizer.db.jooq.tables.TProfile.T_PROFILE;

    /**
     * The table <code>camp.t_profilerole</code>.
     */
    public static final TProfilerole T_PROFILEROLE = de.jottyfan.camporganizer.db.jooq.tables.TProfilerole.T_PROFILEROLE;

    /**
     * The table <code>camp.t_sales</code>.
     */
    public static final TSales T_SALES = de.jottyfan.camporganizer.db.jooq.tables.TSales.T_SALES;

    /**
     * The table <code>camp.t_salescontent</code>.
     */
    public static final TSalescontent T_SALESCONTENT = de.jottyfan.camporganizer.db.jooq.tables.TSalescontent.T_SALESCONTENT;

    /**
     * The table <code>camp.t_salescontenttype</code>.
     */
    public static final TSalescontenttype T_SALESCONTENTTYPE = de.jottyfan.camporganizer.db.jooq.tables.TSalescontenttype.T_SALESCONTENTTYPE;

    /**
     * The table <code>camp.v_budget</code>.
     */
    public static final VBudget V_BUDGET = de.jottyfan.camporganizer.db.jooq.tables.VBudget.V_BUDGET;

    /**
     * The table <code>camp.v_camp</code>.
     */
    public static final VCamp V_CAMP = de.jottyfan.camporganizer.db.jooq.tables.VCamp.V_CAMP;

    /**
     * The table <code>camp.v_profile</code>.
     */
    public static final VProfile V_PROFILE = de.jottyfan.camporganizer.db.jooq.tables.VProfile.V_PROFILE;

    /**
     * The table <code>camp.v_role</code>.
     */
    public static final VRole V_ROLE = de.jottyfan.camporganizer.db.jooq.tables.VRole.V_ROLE;

    /**
     * The table <code>camp.v_sales</code>.
     */
    public static final VSales V_SALES = de.jottyfan.camporganizer.db.jooq.tables.VSales.V_SALES;
}
