/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.TCampdocument;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCampdocumentRecord extends TableRecordImpl<TCampdocumentRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -2003068121;

    /**
     * Setter for <code>camp.t_campdocument.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.t_campdocument.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.t_campdocument.fk_camp</code>.
     */
    public void setFkCamp(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.t_campdocument.fk_camp</code>.
     */
    public Integer getFkCamp() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>camp.t_campdocument.fk_document</code>.
     */
    public void setFkDocument(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.t_campdocument.fk_document</code>.
     */
    public Integer getFkDocument() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TCampdocument.T_CAMPDOCUMENT.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TCampdocument.T_CAMPDOCUMENT.FK_CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TCampdocument.T_CAMPDOCUMENT.FK_DOCUMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getFkDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFkDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampdocumentRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampdocumentRecord value2(Integer value) {
        setFkCamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampdocumentRecord value3(Integer value) {
        setFkDocument(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampdocumentRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TCampdocumentRecord
     */
    public TCampdocumentRecord() {
        super(TCampdocument.T_CAMPDOCUMENT);
    }

    /**
     * Create a detached, initialised TCampdocumentRecord
     */
    public TCampdocumentRecord(Integer pk, Integer fkCamp, Integer fkDocument) {
        super(TCampdocument.T_CAMPDOCUMENT);

        set(0, pk);
        set(1, fkCamp);
        set(2, fkDocument);
    }
}
