/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.enums.EnumModule;
import de.jottyfan.camporganizer.db.jooq.tables.TCampprofile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCampprofileRecord extends TableRecordImpl<TCampprofileRecord> implements Record4<Integer, Integer, Integer, EnumModule> {

    private static final long serialVersionUID = -227452725;

    /**
     * Setter for <code>camp.t_campprofile.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.t_campprofile.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.t_campprofile.fk_profile</code>.
     */
    public void setFkProfile(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.t_campprofile.fk_profile</code>.
     */
    public Integer getFkProfile() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>camp.t_campprofile.fk_camp</code>.
     */
    public void setFkCamp(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.t_campprofile.fk_camp</code>.
     */
    public Integer getFkCamp() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>camp.t_campprofile.module</code>.
     */
    public void setModule(EnumModule value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.t_campprofile.module</code>.
     */
    public EnumModule getModule() {
        return (EnumModule) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, EnumModule> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, EnumModule> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TCampprofile.T_CAMPPROFILE.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TCampprofile.T_CAMPPROFILE.FK_PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TCampprofile.T_CAMPPROFILE.FK_CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumModule> field4() {
        return TCampprofile.T_CAMPPROFILE.MODULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFkProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumModule component4() {
        return getModule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFkProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumModule value4() {
        return getModule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampprofileRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampprofileRecord value2(Integer value) {
        setFkProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampprofileRecord value3(Integer value) {
        setFkCamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampprofileRecord value4(EnumModule value) {
        setModule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampprofileRecord values(Integer value1, Integer value2, Integer value3, EnumModule value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TCampprofileRecord
     */
    public TCampprofileRecord() {
        super(TCampprofile.T_CAMPPROFILE);
    }

    /**
     * Create a detached, initialised TCampprofileRecord
     */
    public TCampprofileRecord(Integer pk, Integer fkProfile, Integer fkCamp, EnumModule module) {
        super(TCampprofile.T_CAMPPROFILE);

        set(0, pk);
        set(1, fkProfile);
        set(2, fkCamp);
        set(3, module);
    }
}
