/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole;
import de.jottyfan.camporganizer.db.jooq.enums.EnumSex;
import de.jottyfan.camporganizer.db.jooq.tables.TPerson;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPersonRecord extends TableRecordImpl<TPersonRecord> implements Record16<Integer, String, String, String, String, String, String, Date, EnumCamprole, String, Integer, Integer, Boolean, Timestamp, EnumSex, Integer> {

    private static final long serialVersionUID = -588909760;

    /**
     * Setter for <code>camp.t_person.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.t_person.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.t_person.forename</code>.
     */
    public void setForename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.t_person.forename</code>.
     */
    public String getForename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>camp.t_person.surname</code>.
     */
    public void setSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.t_person.surname</code>.
     */
    public String getSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>camp.t_person.street</code>.
     */
    public void setStreet(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.t_person.street</code>.
     */
    public String getStreet() {
        return (String) get(3);
    }

    /**
     * Setter for <code>camp.t_person.zip</code>.
     */
    public void setZip(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.t_person.zip</code>.
     */
    public String getZip() {
        return (String) get(4);
    }

    /**
     * Setter for <code>camp.t_person.city</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>camp.t_person.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>camp.t_person.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>camp.t_person.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>camp.t_person.birthdate</code>.
     */
    public void setBirthdate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>camp.t_person.birthdate</code>.
     */
    public Date getBirthdate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>camp.t_person.camprole</code>.
     */
    public void setCamprole(EnumCamprole value) {
        set(8, value);
    }

    /**
     * Getter for <code>camp.t_person.camprole</code>.
     */
    public EnumCamprole getCamprole() {
        return (EnumCamprole) get(8);
    }

    /**
     * Setter for <code>camp.t_person.email</code>.
     */
    public void setEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>camp.t_person.email</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>camp.t_person.fk_camp</code>.
     */
    public void setFkCamp(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>camp.t_person.fk_camp</code>.
     */
    public Integer getFkCamp() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>camp.t_person.fk_profile</code>.
     */
    public void setFkProfile(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>camp.t_person.fk_profile</code>.
     */
    public Integer getFkProfile() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>camp.t_person.accept</code>.
     */
    public void setAccept(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>camp.t_person.accept</code>.
     */
    public Boolean getAccept() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>camp.t_person.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>camp.t_person.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>camp.t_person.sex</code>.
     */
    public void setSex(EnumSex value) {
        set(14, value);
    }

    /**
     * Getter for <code>camp.t_person.sex</code>.
     */
    public EnumSex getSex() {
        return (EnumSex) get(14);
    }

    /**
     * Setter for <code>camp.t_person.fk_registrator</code>.
     */
    public void setFkRegistrator(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>camp.t_person.fk_registrator</code>.
     */
    public Integer getFkRegistrator() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, String, String, Date, EnumCamprole, String, Integer, Integer, Boolean, Timestamp, EnumSex, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, String, String, Date, EnumCamprole, String, Integer, Integer, Boolean, Timestamp, EnumSex, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TPerson.T_PERSON.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TPerson.T_PERSON.FORENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPerson.T_PERSON.SURNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPerson.T_PERSON.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TPerson.T_PERSON.ZIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TPerson.T_PERSON.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TPerson.T_PERSON.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return TPerson.T_PERSON.BIRTHDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumCamprole> field9() {
        return TPerson.T_PERSON.CAMPROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TPerson.T_PERSON.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return TPerson.T_PERSON.FK_CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return TPerson.T_PERSON.FK_PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return TPerson.T_PERSON.ACCEPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return TPerson.T_PERSON.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumSex> field15() {
        return TPerson.T_PERSON.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return TPerson.T_PERSON.FK_REGISTRATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getForename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSurname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumCamprole component9() {
        return getCamprole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getFkProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getAccept();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumSex component15() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getFkRegistrator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getForename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSurname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumCamprole value9() {
        return getCamprole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getFkProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getAccept();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumSex value15() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getFkRegistrator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value2(String value) {
        setForename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value3(String value) {
        setSurname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value4(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value5(String value) {
        setZip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value6(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value7(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value8(Date value) {
        setBirthdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value9(EnumCamprole value) {
        setCamprole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value10(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value11(Integer value) {
        setFkCamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value12(Integer value) {
        setFkProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value13(Boolean value) {
        setAccept(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value14(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value15(EnumSex value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord value16(Integer value) {
        setFkRegistrator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersonRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Date value8, EnumCamprole value9, String value10, Integer value11, Integer value12, Boolean value13, Timestamp value14, EnumSex value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPersonRecord
     */
    public TPersonRecord() {
        super(TPerson.T_PERSON);
    }

    /**
     * Create a detached, initialised TPersonRecord
     */
    public TPersonRecord(Integer pk, String forename, String surname, String street, String zip, String city, String phone, Date birthdate, EnumCamprole camprole, String email, Integer fkCamp, Integer fkProfile, Boolean accept, Timestamp created, EnumSex sex, Integer fkRegistrator) {
        super(TPerson.T_PERSON);

        set(0, pk);
        set(1, forename);
        set(2, surname);
        set(3, street);
        set(4, zip);
        set(5, city);
        set(6, phone);
        set(7, birthdate);
        set(8, camprole);
        set(9, email);
        set(10, fkCamp);
        set(11, fkProfile);
        set(12, accept);
        set(13, created);
        set(14, sex);
        set(15, fkRegistrator);
    }
}
