/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.VBudget;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VBudgetRecord extends TableRecordImpl<VBudgetRecord> implements Record5<BigDecimal, Integer, String, String, Double> {

    private static final long serialVersionUID = 960294198;

    /**
     * Setter for <code>camp.v_budget.budget</code>.
     */
    public void setBudget(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_budget.budget</code>.
     */
    public BigDecimal getBudget() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>camp.v_budget.fk_camp</code>.
     */
    public void setFkCamp(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.v_budget.fk_camp</code>.
     */
    public Integer getFkCamp() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>camp.v_budget.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.v_budget.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>camp.v_budget.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.v_budget.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>camp.v_budget.year</code>.
     */
    public void setYear(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.v_budget.year</code>.
     */
    public Double getYear() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<BigDecimal, Integer, String, String, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<BigDecimal, Integer, String, String, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return VBudget.V_BUDGET.BUDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VBudget.V_BUDGET.FK_CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VBudget.V_BUDGET.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VBudget.V_BUDGET.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VBudget.V_BUDGET.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value1(BigDecimal value) {
        setBudget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value2(Integer value) {
        setFkCamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value4(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value5(Double value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord values(BigDecimal value1, Integer value2, String value3, String value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VBudgetRecord
     */
    public VBudgetRecord() {
        super(VBudget.V_BUDGET);
    }

    /**
     * Create a detached, initialised VBudgetRecord
     */
    public VBudgetRecord(BigDecimal budget, Integer fkCamp, String name, String location, Double year) {
        super(VBudget.V_BUDGET);

        set(0, budget);
        set(1, fkCamp);
        set(2, name);
        set(3, location);
        set(4, year);
    }
}
