/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.enums.EnumDocument;
import de.jottyfan.camporganizer.db.jooq.enums.EnumFiletype;
import de.jottyfan.camporganizer.db.jooq.tables.VCampdocument;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCampdocumentRecord extends TableRecordImpl<VCampdocumentRecord> implements Record8<Integer, String, Timestamp, Integer, String, String, EnumDocument, EnumFiletype> {

    private static final long serialVersionUID = 1790075634;

    /**
     * Setter for <code>camp.v_campdocument.fk_camp</code>.
     */
    public void setFkCamp(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.fk_camp</code>.
     */
    public Integer getFkCamp() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.v_campdocument.campname</code>.
     */
    public void setCampname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.campname</code>.
     */
    public String getCampname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>camp.v_campdocument.arrive</code>.
     */
    public void setArrive(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.arrive</code>.
     */
    public Timestamp getArrive() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>camp.v_campdocument.fk_document</code>.
     */
    public void setFkDocument(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.fk_document</code>.
     */
    public Integer getFkDocument() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>camp.v_campdocument.document</code>.
     */
    public void setDocument(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.document</code>.
     */
    public String getDocument() {
        return (String) get(4);
    }

    /**
     * Setter for <code>camp.v_campdocument.documentname</code>.
     */
    public void setDocumentname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.documentname</code>.
     */
    public String getDocumentname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>camp.v_campdocument.doctype</code>.
     */
    public void setDoctype(EnumDocument value) {
        set(6, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.doctype</code>.
     */
    public EnumDocument getDoctype() {
        return (EnumDocument) get(6);
    }

    /**
     * Setter for <code>camp.v_campdocument.filetype</code>.
     */
    public void setFiletype(EnumFiletype value) {
        set(7, value);
    }

    /**
     * Getter for <code>camp.v_campdocument.filetype</code>.
     */
    public EnumFiletype getFiletype() {
        return (EnumFiletype) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Integer, String, String, EnumDocument, EnumFiletype> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, Integer, String, String, EnumDocument, EnumFiletype> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VCampdocument.V_CAMPDOCUMENT.FK_CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VCampdocument.V_CAMPDOCUMENT.CAMPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return VCampdocument.V_CAMPDOCUMENT.ARRIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return VCampdocument.V_CAMPDOCUMENT.FK_DOCUMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VCampdocument.V_CAMPDOCUMENT.DOCUMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VCampdocument.V_CAMPDOCUMENT.DOCUMENTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumDocument> field7() {
        return VCampdocument.V_CAMPDOCUMENT.DOCTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumFiletype> field8() {
        return VCampdocument.V_CAMPDOCUMENT.FILETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCampname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getArrive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getFkDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDocumentname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumDocument component7() {
        return getDoctype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFiletype component8() {
        return getFiletype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCampname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getArrive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFkDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDocumentname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumDocument value7() {
        return getDoctype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFiletype value8() {
        return getFiletype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value1(Integer value) {
        setFkCamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value2(String value) {
        setCampname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value3(Timestamp value) {
        setArrive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value4(Integer value) {
        setFkDocument(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value5(String value) {
        setDocument(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value6(String value) {
        setDocumentname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value7(EnumDocument value) {
        setDoctype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord value8(EnumFiletype value) {
        setFiletype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampdocumentRecord values(Integer value1, String value2, Timestamp value3, Integer value4, String value5, String value6, EnumDocument value7, EnumFiletype value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VCampdocumentRecord
     */
    public VCampdocumentRecord() {
        super(VCampdocument.V_CAMPDOCUMENT);
    }

    /**
     * Create a detached, initialised VCampdocumentRecord
     */
    public VCampdocumentRecord(Integer fkCamp, String campname, Timestamp arrive, Integer fkDocument, String document, String documentname, EnumDocument doctype, EnumFiletype filetype) {
        super(VCampdocument.V_CAMPDOCUMENT);

        set(0, fkCamp);
        set(1, campname);
        set(2, arrive);
        set(3, fkDocument);
        set(4, document);
        set(5, documentname);
        set(6, doctype);
        set(7, filetype);
    }
}
