/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.VSales;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VSalesRecord extends TableRecordImpl<VSalesRecord> implements Record16<Integer, String, Integer, String, Integer, String, String, Double, Integer, String, BigDecimal, Timestamp, String, byte[], String, String[]> {

    private static final long serialVersionUID = -1025892254;

    /**
     * Setter for <code>camp.v_sales.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_sales.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.v_sales.trader</code>.
     */
    public void setTrader(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.v_sales.trader</code>.
     */
    public String getTrader() {
        return (String) get(1);
    }

    /**
     * Setter for <code>camp.v_sales.fk_camp</code>.
     */
    public void setFkCamp(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.v_sales.fk_camp</code>.
     */
    public Integer getFkCamp() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>camp.v_sales.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.v_sales.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>camp.v_sales.fk_location</code>.
     */
    public void setFkLocation(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.v_sales.fk_location</code>.
     */
    public Integer getFkLocation() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>camp.v_sales.location</code>.
     */
    public void setLocation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>camp.v_sales.location</code>.
     */
    public String getLocation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>camp.v_sales.incredients</code>.
     */
    public void setIncredients(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>camp.v_sales.incredients</code>.
     */
    public String getIncredients() {
        return (String) get(6);
    }

    /**
     * Setter for <code>camp.v_sales.year</code>.
     */
    public void setYear(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>camp.v_sales.year</code>.
     */
    public Double getYear() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>camp.v_sales.fk_sales</code>.
     */
    public void setFkSales(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>camp.v_sales.fk_sales</code>.
     */
    public Integer getFkSales() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>camp.v_sales.provider</code>.
     */
    public void setProvider(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>camp.v_sales.provider</code>.
     */
    public String getProvider() {
        return (String) get(9);
    }

    /**
     * Setter for <code>camp.v_sales.cash</code>.
     */
    public void setCash(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>camp.v_sales.cash</code>.
     */
    public BigDecimal getCash() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>camp.v_sales.buydate</code>.
     */
    public void setBuydate(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>camp.v_sales.buydate</code>.
     */
    public Timestamp getBuydate() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>camp.v_sales.recipenumber</code>.
     */
    public void setRecipenumber(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>camp.v_sales.recipenumber</code>.
     */
    public String getRecipenumber() {
        return (String) get(12);
    }

    /**
     * Setter for <code>camp.v_sales.recipeshot</code>.
     */
    public void setRecipeshot(byte... value) {
        set(13, value);
    }

    /**
     * Getter for <code>camp.v_sales.recipeshot</code>.
     */
    public byte[] getRecipeshot() {
        return (byte[]) get(13);
    }

    /**
     * Setter for <code>camp.v_sales.recipenote</code>.
     */
    public void setRecipenote(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>camp.v_sales.recipenote</code>.
     */
    public String getRecipenote() {
        return (String) get(14);
    }

    /**
     * Setter for <code>camp.v_sales.content</code>.
     */
    public void setContent(String... value) {
        set(15, value);
    }

    /**
     * Getter for <code>camp.v_sales.content</code>.
     */
    public String[] getContent() {
        return (String[]) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, Integer, String, Integer, String, String, Double, Integer, String, BigDecimal, Timestamp, String, byte[], String, String[]> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, Integer, String, Integer, String, String, Double, Integer, String, BigDecimal, Timestamp, String, byte[], String, String[]> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VSales.V_SALES.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VSales.V_SALES.TRADER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VSales.V_SALES.FK_CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VSales.V_SALES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return VSales.V_SALES.FK_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VSales.V_SALES.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VSales.V_SALES.INCREDIENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return VSales.V_SALES.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return VSales.V_SALES.FK_SALES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VSales.V_SALES.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return VSales.V_SALES.CASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return VSales.V_SALES.BUYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return VSales.V_SALES.RECIPENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field14() {
        return VSales.V_SALES.RECIPESHOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VSales.V_SALES.RECIPENOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field16() {
        return VSales.V_SALES.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTrader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getFkLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getIncredients();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getFkSales();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getCash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getBuydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getRecipenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component14() {
        return getRecipeshot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getRecipenote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component16() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTrader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFkCamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getFkLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIncredients();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getFkSales();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getCash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getBuydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRecipenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value14() {
        return getRecipeshot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getRecipenote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value16() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value2(String value) {
        setTrader(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value3(Integer value) {
        setFkCamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value5(Integer value) {
        setFkLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value6(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value7(String value) {
        setIncredients(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value8(Double value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value9(Integer value) {
        setFkSales(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value10(String value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value11(BigDecimal value) {
        setCash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value12(Timestamp value) {
        setBuydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value13(String value) {
        setRecipenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value14(byte... value) {
        setRecipeshot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value15(String value) {
        setRecipenote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value16(String... value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5, String value6, String value7, Double value8, Integer value9, String value10, BigDecimal value11, Timestamp value12, String value13, byte[] value14, String value15, String[] value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VSalesRecord
     */
    public VSalesRecord() {
        super(VSales.V_SALES);
    }

    /**
     * Create a detached, initialised VSalesRecord
     */
    public VSalesRecord(Integer pk, String trader, Integer fkCamp, String name, Integer fkLocation, String location, String incredients, Double year, Integer fkSales, String provider, BigDecimal cash, Timestamp buydate, String recipenumber, byte[] recipeshot, String recipenote, String[] content) {
        super(VSales.V_SALES);

        set(0, pk);
        set(1, trader);
        set(2, fkCamp);
        set(3, name);
        set(4, fkLocation);
        set(5, location);
        set(6, incredients);
        set(7, year);
        set(8, fkSales);
        set(9, provider);
        set(10, cash);
        set(11, buydate);
        set(12, recipenumber);
        set(13, recipeshot);
        set(14, recipenote);
        set(15, content);
    }
}
