/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables;


import de.jottyfan.camporganizer.db.jooq.Camp;
import de.jottyfan.camporganizer.db.jooq.Indexes;
import de.jottyfan.camporganizer.db.jooq.enums.EnumModule;
import de.jottyfan.camporganizer.db.jooq.tables.records.TCampprofileRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCampprofile extends TableImpl<TCampprofileRecord> {

    private static final long serialVersionUID = -1046444136;

    /**
     * The reference instance of <code>camp.t_campprofile</code>
     */
    public static final TCampprofile T_CAMPPROFILE = new TCampprofile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TCampprofileRecord> getRecordType() {
        return TCampprofileRecord.class;
    }

    /**
     * The column <code>camp.t_campprofile.pk</code>.
     */
    public final TableField<TCampprofileRecord, Integer> PK = createField("pk", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>camp.t_campprofile.fk_profile</code>.
     */
    public final TableField<TCampprofileRecord, Integer> FK_PROFILE = createField("fk_profile", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>camp.t_campprofile.fk_camp</code>.
     */
    public final TableField<TCampprofileRecord, Integer> FK_CAMP = createField("fk_camp", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>camp.t_campprofile.module</code>.
     */
    public final TableField<TCampprofileRecord, EnumModule> MODULE = createField("module", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(de.jottyfan.camporganizer.db.jooq.enums.EnumModule.class), this, "");

    /**
     * Create a <code>camp.t_campprofile</code> table reference
     */
    public TCampprofile() {
        this(DSL.name("t_campprofile"), null);
    }

    /**
     * Create an aliased <code>camp.t_campprofile</code> table reference
     */
    public TCampprofile(String alias) {
        this(DSL.name(alias), T_CAMPPROFILE);
    }

    /**
     * Create an aliased <code>camp.t_campprofile</code> table reference
     */
    public TCampprofile(Name alias) {
        this(alias, T_CAMPPROFILE);
    }

    private TCampprofile(Name alias, Table<TCampprofileRecord> aliased) {
        this(alias, aliased, null);
    }

    private TCampprofile(Name alias, Table<TCampprofileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Camp.CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_CAMPPROFILE_PKEY, Indexes.UK_CAMPPROFILE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampprofile as(String alias) {
        return new TCampprofile(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCampprofile as(Name alias) {
        return new TCampprofile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TCampprofile rename(String name) {
        return new TCampprofile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TCampprofile rename(Name name) {
        return new TCampprofile(name, null);
    }
}
