/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables;


import de.jottyfan.camporganizer.db.jooq.Camp;
import de.jottyfan.camporganizer.db.jooq.Indexes;
import de.jottyfan.camporganizer.db.jooq.tables.records.TSalescontentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSalescontent extends TableImpl<TSalescontentRecord> {

    private static final long serialVersionUID = 2115463665;

    /**
     * The reference instance of <code>camp.t_salescontent</code>
     */
    public static final TSalescontent T_SALESCONTENT = new TSalescontent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSalescontentRecord> getRecordType() {
        return TSalescontentRecord.class;
    }

    /**
     * The column <code>camp.t_salescontent.fk_sales</code>.
     */
    public final TableField<TSalescontentRecord, Integer> FK_SALES = createField("fk_sales", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>camp.t_salescontent.fk_salescontenttype</code>.
     */
    public final TableField<TSalescontentRecord, String> FK_SALESCONTENTTYPE = createField("fk_salescontenttype", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>camp.t_salescontent</code> table reference
     */
    public TSalescontent() {
        this(DSL.name("t_salescontent"), null);
    }

    /**
     * Create an aliased <code>camp.t_salescontent</code> table reference
     */
    public TSalescontent(String alias) {
        this(DSL.name(alias), T_SALESCONTENT);
    }

    /**
     * Create an aliased <code>camp.t_salescontent</code> table reference
     */
    public TSalescontent(Name alias) {
        this(alias, T_SALESCONTENT);
    }

    private TSalescontent(Name alias, Table<TSalescontentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TSalescontent(Name alias, Table<TSalescontentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Camp.CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_SALESCONTENT_FK_SALES_FK_SALESCONTENTTYPE_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSalescontent as(String alias) {
        return new TSalescontent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSalescontent as(Name alias) {
        return new TSalescontent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSalescontent rename(String name) {
        return new TSalescontent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSalescontent rename(Name name) {
        return new TSalescontent(name, null);
    }
}
