/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.enums.EnumFiletype;
import de.jottyfan.camporganizer.db.jooq.tables.TPersondocument;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPersondocumentRecord extends TableRecordImpl<TPersondocumentRecord> implements Record5<Integer, Integer, String, String, EnumFiletype> {

    private static final long serialVersionUID = -1760312349;

    /**
     * Setter for <code>camp.t_persondocument.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.t_persondocument.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.t_persondocument.fk_person</code>.
     */
    public void setFkPerson(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.t_persondocument.fk_person</code>.
     */
    public Integer getFkPerson() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>camp.t_persondocument.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.t_persondocument.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>camp.t_persondocument.document</code>.
     */
    public void setDocument(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.t_persondocument.document</code>.
     */
    public String getDocument() {
        return (String) get(3);
    }

    /**
     * Setter for <code>camp.t_persondocument.filetype</code>.
     */
    public void setFiletype(EnumFiletype value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.t_persondocument.filetype</code>.
     */
    public EnumFiletype getFiletype() {
        return (EnumFiletype) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, EnumFiletype> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, EnumFiletype> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TPersondocument.T_PERSONDOCUMENT.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TPersondocument.T_PERSONDOCUMENT.FK_PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPersondocument.T_PERSONDOCUMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPersondocument.T_PERSONDOCUMENT.DOCUMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumFiletype> field5() {
        return TPersondocument.T_PERSONDOCUMENT.FILETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFkPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFiletype component5() {
        return getFiletype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFkPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumFiletype value5() {
        return getFiletype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersondocumentRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersondocumentRecord value2(Integer value) {
        setFkPerson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersondocumentRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersondocumentRecord value4(String value) {
        setDocument(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersondocumentRecord value5(EnumFiletype value) {
        setFiletype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPersondocumentRecord values(Integer value1, Integer value2, String value3, String value4, EnumFiletype value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPersondocumentRecord
     */
    public TPersondocumentRecord() {
        super(TPersondocument.T_PERSONDOCUMENT);
    }

    /**
     * Create a detached, initialised TPersondocumentRecord
     */
    public TPersondocumentRecord(Integer pk, Integer fkPerson, String name, String document, EnumFiletype filetype) {
        super(TPersondocument.T_PERSONDOCUMENT);

        set(0, pk);
        set(1, fkPerson);
        set(2, name);
        set(3, document);
        set(4, filetype);
    }
}
