/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.TRss;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRssRecord extends TableRecordImpl<TRssRecord> implements Record3<String, Timestamp, String> {

    private static final long serialVersionUID = -1594134775;

    /**
     * Setter for <code>camp.t_rss.msg</code>.
     */
    public void setMsg(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.t_rss.msg</code>.
     */
    public String getMsg() {
        return (String) get(0);
    }

    /**
     * Setter for <code>camp.t_rss.regdate</code>.
     */
    public void setRegdate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.t_rss.regdate</code>.
     */
    public Timestamp getRegdate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>camp.t_rss.recipient</code>.
     */
    public void setRecipient(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.t_rss.recipient</code>.
     */
    public String getRecipient() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TRss.T_RSS.MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TRss.T_RSS.REGDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TRss.T_RSS.RECIPIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getRegdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRecipient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRssRecord value1(String value) {
        setMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRssRecord value2(Timestamp value) {
        setRegdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRssRecord value3(String value) {
        setRecipient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRssRecord values(String value1, Timestamp value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRssRecord
     */
    public TRssRecord() {
        super(TRss.T_RSS);
    }

    /**
     * Create a detached, initialised TRssRecord
     */
    public TRssRecord(String msg, Timestamp regdate, String recipient) {
        super(TRss.T_RSS);

        set(0, msg);
        set(1, regdate);
        set(2, recipient);
    }
}
