/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.TRss;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRssRecord extends TableRecordImpl<TRssRecord> implements Record2<String, Timestamp> {

    private static final long serialVersionUID = 2129991710;

    /**
     * Setter for <code>camp.t_rss.msg</code>.
     */
    public void setMsg(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.t_rss.msg</code>.
     */
    public String getMsg() {
        return (String) get(0);
    }

    /**
     * Setter for <code>camp.t_rss.regdate</code>.
     */
    public void setRegdate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.t_rss.regdate</code>.
     */
    public Timestamp getRegdate() {
        return (Timestamp) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Timestamp> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TRss.T_RSS.MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TRss.T_RSS.REGDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getRegdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRssRecord value1(String value) {
        setMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRssRecord value2(Timestamp value) {
        setRegdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRssRecord values(String value1, Timestamp value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRssRecord
     */
    public TRssRecord() {
        super(TRss.T_RSS);
    }

    /**
     * Create a detached, initialised TRssRecord
     */
    public TRssRecord(String msg, Timestamp regdate) {
        super(TRss.T_RSS);

        set(0, msg);
        set(1, regdate);
    }
}
