/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.VBudget;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VBudgetRecord extends TableRecordImpl<VBudgetRecord> implements Record3<BigDecimal, String, Double> {

    private static final long serialVersionUID = 1451659874;

    /**
     * Setter for <code>camp.v_budget.budget</code>.
     */
    public void setBudget(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_budget.budget</code>.
     */
    public BigDecimal getBudget() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>camp.v_budget.location</code>.
     */
    public void setLocation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.v_budget.location</code>.
     */
    public String getLocation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>camp.v_budget.year</code>.
     */
    public void setYear(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.v_budget.year</code>.
     */
    public Double getYear() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigDecimal, String, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return VBudget.V_BUDGET.BUDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VBudget.V_BUDGET.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return VBudget.V_BUDGET.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getBudget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value1(BigDecimal value) {
        setBudget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value2(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord value3(Double value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VBudgetRecord values(BigDecimal value1, String value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VBudgetRecord
     */
    public VBudgetRecord() {
        super(VBudget.V_BUDGET);
    }

    /**
     * Create a detached, initialised VBudgetRecord
     */
    public VBudgetRecord(BigDecimal budget, String location, Double year) {
        super(VBudget.V_BUDGET);

        set(0, budget);
        set(1, location);
        set(2, year);
    }
}
