/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.VCamp;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCampRecord extends TableRecordImpl<VCampRecord> implements Record13<Integer, Boolean, String, Timestamp, Timestamp, Double, String, Integer, Integer, String, String, String, Integer> {

    private static final long serialVersionUID = -18995777;

    /**
     * Setter for <code>camp.v_camp.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_camp.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.v_camp.is_over</code>.
     */
    public void setIsOver(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.v_camp.is_over</code>.
     */
    public Boolean getIsOver() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>camp.v_camp.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.v_camp.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>camp.v_camp.arrive</code>.
     */
    public void setArrive(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.v_camp.arrive</code>.
     */
    public Timestamp getArrive() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>camp.v_camp.depart</code>.
     */
    public void setDepart(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.v_camp.depart</code>.
     */
    public Timestamp getDepart() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>camp.v_camp.year</code>.
     */
    public void setYear(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>camp.v_camp.year</code>.
     */
    public Double getYear() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>camp.v_camp.location_name</code>.
     */
    public void setLocationName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>camp.v_camp.location_name</code>.
     */
    public String getLocationName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>camp.v_camp.min_age</code>.
     */
    public void setMinAge(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>camp.v_camp.min_age</code>.
     */
    public Integer getMinAge() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>camp.v_camp.max_age</code>.
     */
    public void setMaxAge(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>camp.v_camp.max_age</code>.
     */
    public Integer getMaxAge() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>camp.v_camp.url</code>.
     */
    public void setUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>camp.v_camp.url</code>.
     */
    public String getUrl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>camp.v_camp.price</code>.
     */
    public void setPrice(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>camp.v_camp.price</code>.
     */
    public String getPrice() {
        return (String) get(10);
    }

    /**
     * Setter for <code>camp.v_camp.countries</code>.
     */
    public void setCountries(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>camp.v_camp.countries</code>.
     */
    public String getCountries() {
        return (String) get(11);
    }

    /**
     * Setter for <code>camp.v_camp.fk_document</code>.
     */
    public void setFkDocument(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>camp.v_camp.fk_document</code>.
     */
    public Integer getFkDocument() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Boolean, String, Timestamp, Timestamp, Double, String, Integer, Integer, String, String, String, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Boolean, String, Timestamp, Timestamp, Double, String, Integer, Integer, String, String, String, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VCamp.V_CAMP.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return VCamp.V_CAMP.IS_OVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VCamp.V_CAMP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return VCamp.V_CAMP.ARRIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return VCamp.V_CAMP.DEPART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return VCamp.V_CAMP.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VCamp.V_CAMP.LOCATION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return VCamp.V_CAMP.MIN_AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return VCamp.V_CAMP.MAX_AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VCamp.V_CAMP.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VCamp.V_CAMP.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return VCamp.V_CAMP.COUNTRIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return VCamp.V_CAMP.FK_DOCUMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getIsOver();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getArrive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDepart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLocationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getMinAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getMaxAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCountries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getFkDocument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value2(Boolean value) {
        setIsOver(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value4(Timestamp value) {
        setArrive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value5(Timestamp value) {
        setDepart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value6(Double value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value7(String value) {
        setLocationName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value8(Integer value) {
        setMinAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value9(Integer value) {
        setMaxAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value10(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value11(String value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value12(String value) {
        setCountries(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord value13(Integer value) {
        setFkDocument(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCampRecord values(Integer value1, Boolean value2, String value3, Timestamp value4, Timestamp value5, Double value6, String value7, Integer value8, Integer value9, String value10, String value11, String value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VCampRecord
     */
    public VCampRecord() {
        super(VCamp.V_CAMP);
    }

    /**
     * Create a detached, initialised VCampRecord
     */
    public VCampRecord(Integer pk, Boolean isOver, String name, Timestamp arrive, Timestamp depart, Double year, String locationName, Integer minAge, Integer maxAge, String url, String price, String countries, Integer fkDocument) {
        super(VCamp.V_CAMP);

        set(0, pk);
        set(1, isOver);
        set(2, name);
        set(3, arrive);
        set(4, depart);
        set(5, year);
        set(6, locationName);
        set(7, minAge);
        set(8, maxAge);
        set(9, url);
        set(10, price);
        set(11, countries);
        set(12, fkDocument);
    }
}
