/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole;
import de.jottyfan.camporganizer.db.jooq.tables.VCamprole;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCamproleRecord extends TableRecordImpl<VCamproleRecord> implements Record1<EnumCamprole> {

    private static final long serialVersionUID = -1136956420;

    /**
     * Setter for <code>camp.v_camprole.name</code>.
     */
    public void setName(EnumCamprole value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_camprole.name</code>.
     */
    public EnumCamprole getName() {
        return (EnumCamprole) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<EnumCamprole> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<EnumCamprole> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumCamprole> field1() {
        return VCamprole.V_CAMPROLE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumCamprole component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumCamprole value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCamproleRecord value1(EnumCamprole value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCamproleRecord values(EnumCamprole value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VCamproleRecord
     */
    public VCamproleRecord() {
        super(VCamprole.V_CAMPROLE);
    }

    /**
     * Create a detached, initialised VCamproleRecord
     */
    public VCamproleRecord(EnumCamprole name) {
        super(VCamprole.V_CAMPROLE);

        set(0, name);
    }
}
