/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole;
import de.jottyfan.camporganizer.db.jooq.tables.VRegistration;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VRegistrationRecord extends TableRecordImpl<VRegistrationRecord> implements Record11<Integer, String, String, String, String, String, String, Date, EnumCamprole, String, String> {

    private static final long serialVersionUID = -2104875306;

    /**
     * Setter for <code>camp.v_registration.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_registration.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.v_registration.forename</code>.
     */
    public void setForename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.v_registration.forename</code>.
     */
    public String getForename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>camp.v_registration.surname</code>.
     */
    public void setSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.v_registration.surname</code>.
     */
    public String getSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>camp.v_registration.street</code>.
     */
    public void setStreet(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.v_registration.street</code>.
     */
    public String getStreet() {
        return (String) get(3);
    }

    /**
     * Setter for <code>camp.v_registration.zip</code>.
     */
    public void setZip(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.v_registration.zip</code>.
     */
    public String getZip() {
        return (String) get(4);
    }

    /**
     * Setter for <code>camp.v_registration.city</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>camp.v_registration.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>camp.v_registration.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>camp.v_registration.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>camp.v_registration.birthdate</code>.
     */
    public void setBirthdate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>camp.v_registration.birthdate</code>.
     */
    public Date getBirthdate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>camp.v_registration.camprole</code>.
     */
    public void setCamprole(EnumCamprole value) {
        set(8, value);
    }

    /**
     * Getter for <code>camp.v_registration.camprole</code>.
     */
    public EnumCamprole getCamprole() {
        return (EnumCamprole) get(8);
    }

    /**
     * Setter for <code>camp.v_registration.email</code>.
     */
    public void setEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>camp.v_registration.email</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>camp.v_registration.campname</code>.
     */
    public void setCampname(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>camp.v_registration.campname</code>.
     */
    public String getCampname() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, Date, EnumCamprole, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, Date, EnumCamprole, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VRegistration.V_REGISTRATION.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VRegistration.V_REGISTRATION.FORENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VRegistration.V_REGISTRATION.SURNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VRegistration.V_REGISTRATION.STREET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VRegistration.V_REGISTRATION.ZIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VRegistration.V_REGISTRATION.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VRegistration.V_REGISTRATION.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return VRegistration.V_REGISTRATION.BIRTHDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EnumCamprole> field9() {
        return VRegistration.V_REGISTRATION.CAMPROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VRegistration.V_REGISTRATION.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VRegistration.V_REGISTRATION.CAMPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getForename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSurname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStreet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EnumCamprole value9() {
        return getCamprole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCampname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value2(String value) {
        setForename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value3(String value) {
        setSurname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value4(String value) {
        setStreet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value5(String value) {
        setZip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value6(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value7(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value8(Date value) {
        setBirthdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value9(EnumCamprole value) {
        setCamprole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value10(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord value11(String value) {
        setCampname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRegistrationRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Date value8, EnumCamprole value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VRegistrationRecord
     */
    public VRegistrationRecord() {
        super(VRegistration.V_REGISTRATION);
    }

    /**
     * Create a detached, initialised VRegistrationRecord
     */
    public VRegistrationRecord(Integer pk, String forename, String surname, String street, String zip, String city, String phone, Date birthdate, EnumCamprole camprole, String email, String campname) {
        super(VRegistration.V_REGISTRATION);

        set(0, pk);
        set(1, forename);
        set(2, surname);
        set(3, street);
        set(4, zip);
        set(5, city);
        set(6, phone);
        set(7, birthdate);
        set(8, camprole);
        set(9, email);
        set(10, campname);
    }
}
