/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables.records;


import de.jottyfan.camporganizer.db.jooq.tables.VSales;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VSalesRecord extends TableRecordImpl<VSalesRecord> implements Record12<Integer, String, String, String, Double, String, BigDecimal, Timestamp, String, byte[], String, String[]> {

    private static final long serialVersionUID = -894017285;

    /**
     * Setter for <code>camp.v_sales.pk</code>.
     */
    public void setPk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>camp.v_sales.pk</code>.
     */
    public Integer getPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>camp.v_sales.trader</code>.
     */
    public void setTrader(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>camp.v_sales.trader</code>.
     */
    public String getTrader() {
        return (String) get(1);
    }

    /**
     * Setter for <code>camp.v_sales.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>camp.v_sales.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>camp.v_sales.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>camp.v_sales.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>camp.v_sales.year</code>.
     */
    public void setYear(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>camp.v_sales.year</code>.
     */
    public Double getYear() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>camp.v_sales.provider</code>.
     */
    public void setProvider(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>camp.v_sales.provider</code>.
     */
    public String getProvider() {
        return (String) get(5);
    }

    /**
     * Setter for <code>camp.v_sales.cash</code>.
     */
    public void setCash(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>camp.v_sales.cash</code>.
     */
    public BigDecimal getCash() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>camp.v_sales.buydate</code>.
     */
    public void setBuydate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>camp.v_sales.buydate</code>.
     */
    public Timestamp getBuydate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>camp.v_sales.recipenumber</code>.
     */
    public void setRecipenumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>camp.v_sales.recipenumber</code>.
     */
    public String getRecipenumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>camp.v_sales.recipeshot</code>.
     */
    public void setRecipeshot(byte... value) {
        set(9, value);
    }

    /**
     * Getter for <code>camp.v_sales.recipeshot</code>.
     */
    public byte[] getRecipeshot() {
        return (byte[]) get(9);
    }

    /**
     * Setter for <code>camp.v_sales.recipenote</code>.
     */
    public void setRecipenote(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>camp.v_sales.recipenote</code>.
     */
    public String getRecipenote() {
        return (String) get(10);
    }

    /**
     * Setter for <code>camp.v_sales.content</code>.
     */
    public void setContent(String... value) {
        set(11, value);
    }

    /**
     * Getter for <code>camp.v_sales.content</code>.
     */
    public String[] getContent() {
        return (String[]) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Double, String, BigDecimal, Timestamp, String, byte[], String, String[]> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Double, String, BigDecimal, Timestamp, String, byte[], String, String[]> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VSales.V_SALES.PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VSales.V_SALES.TRADER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VSales.V_SALES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VSales.V_SALES.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VSales.V_SALES.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VSales.V_SALES.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return VSales.V_SALES.CASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return VSales.V_SALES.BUYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VSales.V_SALES.RECIPENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field10() {
        return VSales.V_SALES.RECIPESHOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VSales.V_SALES.RECIPENOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field12() {
        return VSales.V_SALES.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTrader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getCash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getBuydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRecipenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value10() {
        return getRecipeshot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRecipenote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value12() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value1(Integer value) {
        setPk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value2(String value) {
        setTrader(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value4(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value5(Double value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value6(String value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value7(BigDecimal value) {
        setCash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value8(Timestamp value) {
        setBuydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value9(String value) {
        setRecipenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value10(byte... value) {
        setRecipeshot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value11(String value) {
        setRecipenote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord value12(String... value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSalesRecord values(Integer value1, String value2, String value3, String value4, Double value5, String value6, BigDecimal value7, Timestamp value8, String value9, byte[] value10, String value11, String[] value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VSalesRecord
     */
    public VSalesRecord() {
        super(VSales.V_SALES);
    }

    /**
     * Create a detached, initialised VSalesRecord
     */
    public VSalesRecord(Integer pk, String trader, String name, String location, Double year, String provider, BigDecimal cash, Timestamp buydate, String recipenumber, byte[] recipeshot, String recipenote, String[] content) {
        super(VSales.V_SALES);

        set(0, pk);
        set(1, trader);
        set(2, name);
        set(3, location);
        set(4, year);
        set(5, provider);
        set(6, cash);
        set(7, buydate);
        set(8, recipenumber);
        set(9, recipeshot);
        set(10, recipenote);
        set(11, content);
    }
}
