/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables;


import de.jottyfan.camporganizer.db.jooq.Camp;
import de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole;
import de.jottyfan.camporganizer.db.jooq.tables.records.VCamproleRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VCamprole extends TableImpl<VCamproleRecord> {

    private static final long serialVersionUID = 624651828;

    /**
     * The reference instance of <code>camp.v_camprole</code>
     */
    public static final VCamprole V_CAMPROLE = new VCamprole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VCamproleRecord> getRecordType() {
        return VCamproleRecord.class;
    }

    /**
     * The column <code>camp.v_camprole.name</code>.
     */
    public final TableField<VCamproleRecord, EnumCamprole> NAME = createField("name", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole.class), this, "");

    /**
     * Create a <code>camp.v_camprole</code> table reference
     */
    public VCamprole() {
        this("v_camprole", null);
    }

    /**
     * Create an aliased <code>camp.v_camprole</code> table reference
     */
    public VCamprole(String alias) {
        this(alias, V_CAMPROLE);
    }

    private VCamprole(String alias, Table<VCamproleRecord> aliased) {
        this(alias, aliased, null);
    }

    private VCamprole(String alias, Table<VCamproleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Camp.CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VCamprole as(String alias) {
        return new VCamprole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VCamprole rename(String name) {
        return new VCamprole(name, null);
    }
}
