/*
 * This file is generated by jOOQ.
*/
package de.jottyfan.camporganizer.db.jooq.tables;


import de.jottyfan.camporganizer.db.jooq.Camp;
import de.jottyfan.camporganizer.db.jooq.enums.EnumRole;
import de.jottyfan.camporganizer.db.jooq.tables.records.VProfileRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VProfile extends TableImpl<VProfileRecord> {

    private static final long serialVersionUID = -2105591939;

    /**
     * The reference instance of <code>camp.v_profile</code>
     */
    public static final VProfile V_PROFILE = new VProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VProfileRecord> getRecordType() {
        return VProfileRecord.class;
    }

    /**
     * The column <code>camp.v_profile.pk</code>.
     */
    public final TableField<VProfileRecord, Integer> PK = createField("pk", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>camp.v_profile.forename</code>.
     */
    public final TableField<VProfileRecord, String> FORENAME = createField("forename", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>camp.v_profile.surname</code>.
     */
    public final TableField<VProfileRecord, String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>camp.v_profile.username</code>.
     */
    public final TableField<VProfileRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>camp.v_profile.password</code>.
     */
    public final TableField<VProfileRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>camp.v_profile.roles</code>.
     */
    public final TableField<VProfileRecord, EnumRole[]> ROLES = createField("roles", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(de.jottyfan.camporganizer.db.jooq.enums.EnumRole.class).getArrayDataType(), this, "");

    /**
     * Create a <code>camp.v_profile</code> table reference
     */
    public VProfile() {
        this("v_profile", null);
    }

    /**
     * Create an aliased <code>camp.v_profile</code> table reference
     */
    public VProfile(String alias) {
        this(alias, V_PROFILE);
    }

    private VProfile(String alias, Table<VProfileRecord> aliased) {
        this(alias, aliased, null);
    }

    private VProfile(String alias, Table<VProfileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Camp.CAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VProfile as(String alias) {
        return new VProfile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VProfile rename(String name) {
        return new VProfile(name, null);
    }
}
